input {
  kafka {
    bootstrap_servers => "kafka-1:29092"
    topics => ["results"]
    codec => json                 
    group_id => "logstash-results"
    auto_offset_reset => "earliest"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "sentence_results"
    document_id => "%{id}"
  }
  stdout { codec => rubydebug }
}